import {Document, Page, Text, View, StyleSheet} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 50,
    fontFamily: "Helvetica",
  },
  headerContainer: {
    alignItems: "center",
    marginBottom: 40,
  },
  universityTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 10,
    textTransform: "uppercase",
  },
  labReportTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 30,
    textDecoration: "underline",
  },
  courseContainer: {
    marginBottom: 40,
  },
  row: {
    flexDirection: "row",
    marginBottom: 8,
  },
  label: {
    width: 120,
    fontSize: 12,
    fontWeight: "bold",
  },
  value: {
    flex: 1,
    fontSize: 12,
  },
  peopleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 40,
  },
  personColumn: {
    width: "45%",
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 15,
    textDecoration: "underline",
  },
  personDetail: {
    fontSize: 12,
    marginBottom: 5,
  },
  footer: {
    position: "absolute",
    bottom: 50,
    left: 50,
    right: 50,
    textAlign: "center",
    fontSize: 10,
    color: "gray",
  },
});

export default function CoverPageDocument({
  template,
  user,
}: {
  template: any;
  user: any;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerContainer}>
          <Text style={styles.universityTitle}>University Name Here</Text>
          <Text style={styles.labReportTitle}>LABORATORY REPORT</Text>
        </View>

        <View style={styles.courseContainer}>
          <View style={styles.row}>
            <Text style={styles.label}>Course Number:</Text>
            <Text style={styles.value}>{template.courseNumber}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Course Title:</Text>
            <Text style={styles.value}>{template.courseTitle}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Session/Term:</Text>
            <Text style={styles.value}>{template.sessionTerm}</Text>
          </View>
        </View>

        <View style={styles.peopleContainer}>
          <View style={styles.personColumn}>
            <Text style={styles.sectionTitle}>Submitted By:</Text>
            <Text style={styles.personDetail}>Name: {user.name}</Text>
            <Text style={styles.personDetail}>
              Student ID: {user.studentId}
            </Text>
            <Text style={styles.personDetail}>
              Department: {user.department}
            </Text>
            <Text style={styles.personDetail}>
              Level: {user.level} | Term: {user.term}
            </Text>
            <Text style={styles.personDetail}>Section: {user.section}</Text>
          </View>

          <View style={styles.personColumn}>
            <Text style={styles.sectionTitle}>Submitted To:</Text>
            <Text style={styles.personDetail}>{template.teacher1Name}</Text>
            <Text style={styles.personDetail}>
              {template.teacher1Designation}
            </Text>

            {template.teacher2Name && (
              <View style={{marginTop: 10}}>
                <Text style={styles.personDetail}>{template.teacher2Name}</Text>
                <Text style={styles.personDetail}>
                  {template.teacher2Designation}
                </Text>
              </View>
            )}
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by CoverIt Cover Page Generator
        </Text>
      </Page>
    </Document>
  );
}
