"use client";

import {Control, useFieldArray, UseFormRegister, FieldErrors} from "react-hook-form";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Plus, Trash2, ListOrdered} from "lucide-react";
import {cn} from "@/lib/utils";

interface ExperimentNamesInputProps {
  control: Control<any>;
  register: UseFormRegister<any>;
  errors: FieldErrors<any>;
  disabled?: boolean;
}

export function ExperimentNamesInput({
  control,
  register,
  errors,
  disabled,
}: ExperimentNamesInputProps) {
  const {fields, append, remove} = useFieldArray({
    control,
    name: "experimentNames",
  });

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <ListOrdered className="size-5 text-primary" />
          <h3 className="font-medium text-lg">Experiments</h3>
        </div>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => append("")}
          disabled={disabled}
          className="h-8 gap-1"
        >
          <Plus className="size-4" />
          Add Experiment
        </Button>
      </div>

      <div className={cn("space-y-3", fields.length > 0 && "border p-4 rounded-lg bg-muted/30")}>
        {fields.length === 0 ? (
          <p className="text-sm text-muted-foreground italic text-center py-4">
            No experiments added. 12 blank rows will be generated by default.
          </p>
        ) : (
          <div className="space-y-3">
            {fields.map((field, index) => (
              <div key={field.id} className="flex items-start gap-2">
                <div className="pt-2 text-sm font-medium text-muted-foreground w-6">
                  {index + 1}.
                </div>
                <div className="flex-1 space-y-1">
                  <Input
                    {...register(`experimentNames.${index}` as const)}
                    placeholder={`Experiment ${index + 1} name...`}
                    disabled={disabled}
                    className="bg-background"
                  />
                  {errors.experimentNames?.[index] && (
                    <p className="text-xs text-destructive">
                      {(errors.experimentNames[index] as any).message}
                    </p>
                  )}
                </div>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => remove(index)}
                  disabled={disabled}
                  className="size-9 text-muted-foreground hover:text-destructive transition-colors"
                >
                  <Trash2 className="size-4" />
                </Button>
              </div>
            ))}
          </div>
        )}
      </div>
      
      {fields.length > 0 && (
        <p className="text-[11px] text-muted-foreground">
          Tip: Leave experiment names blank if you want to provide a numbered empty row.
        </p>
      )}
    </div>
  );
}
