import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {Card, CardContent, CardHeader, CardTitle, CardDescription} from "@/components/ui/card";
import {formatDistanceToNow} from "date-fns";

interface DownloadItem {
  id: string;
  templateName: string | null;
  userName: string | null;
  downloadedAt: Date;
}

interface Props {
  downloads: DownloadItem[];
}

export function RecentDownloadsTable({downloads}: Props) {
  return (
    <Card className="flex-1 border-border/50 bg-card/60 backdrop-blur-md transition-all duration-200 hover:shadow-md hover:border-border/80">
      <CardHeader>
        <CardTitle className="font-heading font-semibold text-base text-foreground">
          Recent Downloads
        </CardTitle>
        <CardDescription className="text-xs text-muted-foreground">
          Latest top sheets generated by users
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="overflow-hidden rounded-lg border border-border/40 bg-card/40">
          <Table>
            <TableHeader>
              <TableRow className="hover:bg-transparent">
                <TableHead>Template</TableHead>
                <TableHead>User</TableHead>
                <TableHead className="text-right">Time</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {downloads.map((d) => (
                <TableRow key={d.id} className="border-border/40 hover:bg-muted/30 transition-colors">
                  <TableCell className="font-semibold text-sm text-foreground truncate max-w-[150px]">
                    {d.templateName || "Unknown Template"}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground truncate max-w-[120px]">
                    {d.userName || "Unknown User"}
                  </TableCell>
                  <TableCell className="text-right text-[11px] text-muted-foreground pr-4 whitespace-nowrap">
                    {formatDistanceToNow(new Date(d.downloadedAt), {addSuffix: true})}
                  </TableCell>
                </TableRow>
              ))}
              {downloads.length === 0 && (
                <TableRow className="hover:bg-transparent">
                  <TableCell colSpan={3} className="h-28 text-center text-muted-foreground text-xs">
                    No downloads recorded.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  );
}
